[pytest]
addopts = -s -v
# Опция для автоматического добавления флагов
python_files =  test_*.py
# Устанавливает правила для тестовых файлов
python_classes = Test*
# Устанавливает правила для имен классов
python_functions = test_*
# Устанавливает правила для имен функций

markers =
    regression: Маркировка для регрессионных тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.
    courses: Маркировка для тестов, связанных с курсами.
    dashboard: Маркировка для тестов, связанных с рабочей панелью.



